import type { QuestionInput } from '../../src/lib/question-input';

// Each tuple is authored individually. The first option is the intended answer;
// buildQuestions rotates choices and derives keys from the option identity.
type Single = [string, string, string[], string];
export const twk: Single[] = [
  ['NASIONALISME', 'Panitia festival kota ingin menampilkan budaya dari beberapa kelompok warga. Usul yang paling mendukung persatuan adalah ...', ['Memberi ruang bagi tiap kelompok untuk memperkenalkan budayanya dalam acara bersama.', 'Menampilkan hanya budaya kelompok terbanyak agar acara seragam.', 'Membagi acara menjadi kelompok yang tidak saling berinteraksi.', 'Meniadakan seluruh unsur budaya agar tidak perlu berdiskusi.', 'Memilih budaya berdasarkan besarnya sumbangan peserta.'], 'Ruang yang setara dan kegiatan bersama memungkinkan warga saling mengenal tanpa menghapus identitas budaya. Keseragaman atau besarnya sumbangan bukan dasar persatuan.'],
  ['NASIONALISME', 'Beredar pesan yang menuduh seluruh warga suatu daerah sebagai pelaku penipuan berdasarkan satu kasus. Respons yang paling mendukung persatuan adalah ...', ['Memeriksa sumber dan menolak generalisasi terhadap warga daerah tersebut.', 'Meneruskan pesan dengan tambahan tanda tanya.', 'Membalas dengan tuduhan terhadap daerah lain.', 'Menganggap semua warga daerah itu perlu dicurigai.', 'Mengubah nama daerah dalam pesan lalu menyebarkannya.'], 'Perbuatan individu tidak membenarkan tuduhan terhadap seluruh kelompok. Verifikasi dan penolakan generalisasi mengurangi prasangka antardaerah.'],
  ['NASIONALISME', 'Tim relawan terdiri atas anggota dari berbagai daerah yang baru saling mengenal. Dasar pembagian tugas yang paling memperkuat kerja bersama adalah ...', ['Kebutuhan kegiatan dan kemampuan anggota tanpa membedakan asal daerah.', 'Kesamaan asal daerah dengan ketua tim.', 'Urutan daerah menurut jumlah penduduk.', 'Kedekatan keluarga dengan panitia.', 'Stereotip kemampuan tiap suku.'], 'Pembagian berdasarkan kemampuan dan kebutuhan menempatkan semua anggota sebagai rekan setara. Asal daerah dan stereotip tidak menentukan kecakapan individu.'],
  ['NASIONALISME', 'Seorang peserta diskusi menyampaikan kritik berbasis data terhadap layanan pemerintah. Sikap yang tepat dalam kehidupan kebangsaan adalah ...', ['Menanggapi substansi kritik secara terbuka dan menggunakannya untuk perbaikan.', 'Menganggap kritik apa pun sebagai penolakan terhadap negara.', 'Melarang peserta berbicara karena berbeda pendapat.', 'Mengganti pembahasan dengan serangan pribadi.', 'Menghapus data agar tidak ada perbedaan pandangan.'], 'Kepedulian terhadap negara dapat diwujudkan melalui kritik yang bertanggung jawab. Membahas substansinya membantu perbaikan layanan dan menghormati perbedaan pendapat.'],
  ['NASIONALISME', 'Dua kelompok warga mengusulkan penggunaan balai bersama pada waktu yang sama. Cara menjaga kepentingan bersama adalah ...', ['Memusyawarahkan jadwal dengan aturan pemakaian yang berlaku sama untuk semua.', 'Selalu mendahulukan kelompok yang lebih lama menetap.', 'Memberikan akses hanya kepada pendukung pengurus.', 'Membiarkan kelompok terkuat menentukan sendiri.', 'Menutup balai secara permanen agar tidak digunakan siapa pun.'], 'Aturan yang setara dan musyawarah menjaga fasilitas sebagai milik bersama. Senioritas, dukungan politik, dan kekuatan kelompok bukan dasar perlakuan istimewa.'],
  ['NASIONALISME', 'Warga dari luar daerah ikut dalam kerja bakti lingkungan. Sikap yang paling menunjukkan rasa kebangsaan yang inklusif adalah ...', ['Mengajak mereka merencanakan dan melaksanakan kegiatan bersama warga lain.', 'Meminta mereka bekerja terpisah dari warga lama.', 'Menerima bantuannya tetapi melarang mereka memberi usul.', 'Menilai kepedulian hanya dari tempat kelahiran.', 'Menyerahkan seluruh pekerjaan kepada pendatang.'], 'Keterlibatan yang setara menumbuhkan rasa memiliki lingkungan bersama. Tempat kelahiran tidak mengurangi kesempatan berkontribusi.'],
  ['INTEGRITAS', 'Laporan biaya perjalanan memuat pengeluaran pribadi yang tidak boleh dibebankan kepada kantor. Penanggung jawab meminta Anda tetap memasukkannya. Tindakan berintegritas adalah ...', ['Menolak memasukkan biaya itu dan mencatat pengeluaran sesuai bukti yang sah.', 'Memasukkannya karena perintah atasan.', 'Mengganti uraian biaya agar terlihat seperti kebutuhan dinas.', 'Membagi biaya tersebut ke beberapa kuitansi.', 'Menghilangkan bukti agar sulit diperiksa.'], 'Kejujuran pelaporan menuntut kesesuaian biaya, bukti, dan peruntukan. Perintah atasan tidak membenarkan pemalsuan uraian atau dokumen.'],
  ['INTEGRITAS', 'Anda menjadi penilai proposal dan mengetahui salah satu pengusul adalah saudara dekat. Langkah yang paling menjaga integritas penilaian adalah ...', ['Mengungkap hubungan tersebut dan meminta pengaturan penilai lain sesuai prosedur.', 'Memberi nilai tinggi karena mengenal pengusul.', 'Memberi nilai rendah agar tampak netral.', 'Menyembunyikan hubungan selama tidak ditanya.', 'Meminta saudara mengganti nama pengusul saja.'], 'Pengungkapan konflik kepentingan memungkinkan pengaturan penilaian yang independen. Nilai sengaja dinaikkan atau diturunkan tetap menyimpangkan penilaian.'],
  ['INTEGRITAS', 'Setelah laporan diterima, Anda menemukan jumlah peserta tercatat lebih besar daripada daftar hadir. Anda sebaiknya ...', ['Mengajukan koreksi dengan daftar hadir pendukung dan penjelasan kesalahan.', 'Membiarkan karena laporan sudah diterima.', 'Menambah nama fiktif agar jumlah cocok.', 'Menghapus daftar hadir asli.', 'Menyalahkan petugas lain tanpa memeriksa proses.'], 'Koreksi yang dapat ditelusuri memulihkan ketepatan laporan. Mengubah bukti agar sesuai laporan justru menambah ketidakjujuran.'],
  ['INTEGRITAS', 'Teman meminta Anda mencatat kehadirannya meskipun ia tidak datang. Respons yang sesuai integritas adalah ...', ['Menolak pencatatan palsu dan menyarankan ia menjelaskan ketidakhadiran melalui prosedur.', 'Mencatat hadir karena hanya sekali.', 'Mencatat hadir jika teman bersedia menggantikan Anda nanti.', 'Meminta orang lain melakukan pencatatan palsu.', 'Mencatat hadir tetapi tidak memberitahukannya.'], 'Catatan kehadiran harus mencerminkan keadaan sebenarnya. Hubungan pertemanan atau imbal balik tidak membenarkan data palsu.'],
  ['INTEGRITAS', 'Seorang pemasok menawarkan hadiah dengan syarat informasi evaluasi pesaing dibocorkan. Tindakan yang menjaga integritas adalah ...', ['Menolak tawaran dan melaporkannya melalui jalur yang berwenang.', 'Menerima hadiah tanpa memberitahukan seluruh informasi.', 'Memberikan informasi jika nilainya kecil.', 'Meminta hadiah dikirim setelah evaluasi selesai.', 'Menyampaikan informasi melalui teman.'], 'Tawaran mengaitkan hadiah dengan penyalahgunaan informasi. Penolakan dan pelaporan menjaga kerahasiaan serta keadilan proses evaluasi.'],
  ['INTEGRITAS', 'Dalam presentasi tim, karya rekan keliru disebut sebagai karya Anda. Respons yang jujur adalah ...', ['Meluruskan pembagian kontribusi dan memberi pengakuan kepada rekan.', 'Membiarkannya karena menguntungkan penilaian Anda.', 'Mengaku sebagai pembimbing meskipun tidak terlibat.', 'Mengubah berkas agar nama rekan hilang.', 'Meminta rekan tidak membahasnya.'], 'Integritas mencakup pengakuan kontribusi secara akurat. Menerima penghargaan atas karya orang lain tanpa meluruskan informasi tidak jujur.'],
  ['BELA_NEGARA', 'Sekolah menyelenggarakan latihan evakuasi bencana. Bentuk kontribusi yang paling bertanggung jawab adalah ...', ['Mengikuti latihan, memahami jalur evakuasi, dan membantu sesuai arahan petugas.', 'Mengabaikan latihan karena belum ada bencana.', 'Membuat informasi lokasi aman tanpa memeriksa keadaan.', 'Menghalangi jalur keluar untuk merekam kegiatan.', 'Mengubah titik kumpul secara sepihak.'], 'Kesiapsiagaan dan kepatuhan pada koordinasi keselamatan membantu melindungi masyarakat. Informasi atau perubahan sepihak dapat membahayakan evakuasi.'],
  ['BELA_NEGARA', 'Saat banjir, jalur bantuan harus digunakan bersama banyak relawan. Tindakan yang paling mendukung keselamatan masyarakat adalah ...', ['Berkoordinasi dengan posko agar bantuan sesuai kebutuhan dan jalur tetap terbuka.', 'Mengirim seluruh bantuan ke lokasi yang paling mudah difoto.', 'Menutup jalur bagi kelompok relawan lain.', 'Membagikan barang tanpa memperhatikan kebutuhan korban.', 'Masuk ke wilayah berbahaya tanpa arahan petugas.'], 'Koordinasi mencegah tumpang tindih bantuan dan menjaga akses darurat. Kepentingan dokumentasi tidak boleh mengalahkan kebutuhan korban.'],
  ['BELA_NEGARA', 'Anda melihat kerusakan pada jembatan umum yang berpotensi membahayakan pengguna. Kontribusi warga yang tepat adalah ...', ['Melaporkan lokasi dan kondisi kepada pihak berwenang serta memperingatkan pengguna secara aman.', 'Menyebarkan perkiraan penyebab sebagai fakta.', 'Membongkar jembatan sendiri tanpa keahlian.', 'Membiarkan karena bukan milik pribadi.', 'Menghalangi petugas yang hendak memeriksa.'], 'Laporan yang jelas membantu penanganan dan peringatan aman mengurangi risiko. Perbaikan berisiko memerlukan kewenangan dan keahlian.'],
  ['BELA_NEGARA', 'Pesan berantai menyebut akan terjadi gangguan keamanan malam ini tanpa sumber yang jelas. Sikap bertanggung jawab adalah ...', ['Memeriksa informasi pada kanal berwenang sebelum menyebarkannya.', 'Meneruskannya ke semua grup agar cepat viral.', 'Menambahkan cerita agar warga lebih waspada.', 'Menuduh kelompok tertentu sebagai penyebab.', 'Membuat pengumuman darurat sendiri tanpa verifikasi.'], 'Verifikasi mengurangi kepanikan dan tuduhan tanpa dasar. Kewaspadaan harus didukung informasi yang dapat dipertanggungjawabkan.'],
  ['BELA_NEGARA', 'Dalam pelatihan pertolongan pertama, peserta belum memahami satu prosedur. Tindakan yang mendukung kesiapan menolong adalah ...', ['Meminta demonstrasi ulang dan berlatih di bawah pengawasan instruktur.', 'Mengaku paham agar cepat mendapat sertifikat.', 'Mengajarkan prosedur yang belum dipahami kepada orang lain.', 'Mencoba tindakan berisiko pada korban nyata.', 'Menghafal nama alat tanpa memahami penggunaannya.'], 'Keterampilan yang dilatih dengan benar lebih berguna daripada pengakuan kemampuan semu. Pengawasan mengurangi risiko kesalahan saat belajar.'],
  ['BELA_NEGARA', 'Program lingkungan mengajak warga menjaga sumber air bersama. Partisipasi yang paling mendukung keberlanjutan adalah ...', ['Mengikuti pengelolaan sampah dan melaporkan pencemaran berdasarkan pengamatan.', 'Membuang limbah sedikit demi sedikit agar tidak terlihat.', 'Menutup akses air untuk kepentingan pribadi.', 'Menyerahkan semua tanggung jawab kepada warga lain.', 'Membersihkan hanya saat ada dokumentasi pejabat.'], 'Menjaga sumber daya bersama membutuhkan kebiasaan berkelanjutan dan laporan yang faktual. Kepentingan pribadi tidak boleh merusak akses masyarakat.'],
  ['PILAR_NEGARA', 'Panitia menyediakan waktu agar anggota dapat beribadah sesuai keyakinan masing-masing. Nilai Pancasila yang paling langsung tercermin adalah ...', ['Ketuhanan Yang Maha Esa.', 'Keadilan sosial dalam pembagian pendapatan.', 'Permusyawaratan dalam pemilihan ketua.', 'Persatuan dalam penggunaan bahasa bersama.', 'Kemanusiaan dalam pertolongan kecelakaan.'], 'Menghormati pelaksanaan ibadah berkaitan langsung dengan nilai Ketuhanan. Contoh pada pilihan lain menjelaskan penerapan nilai yang berbeda.'],
  ['PILAR_NEGARA', 'Korban kecelakaan ditolong tanpa membedakan asal dan kedudukannya. Nilai utama yang dicontohkan adalah ...', ['Kemanusiaan yang adil dan beradab.', 'Persaingan ekonomi antarwarga.', 'Pengambilan keputusan berdasarkan suara terbanyak.', 'Kewajiban mengikuti organisasi tertentu.', 'Keutamaan kepentingan kelompok sendiri.'], 'Pertolongan tanpa diskriminasi menghormati martabat manusia. Pilihan lain tidak menjelaskan nilai kemanusiaan dalam situasi tersebut.'],
  ['PILAR_NEGARA', 'Rapat lingkungan memberi kesempatan peserta menjelaskan alasan sebelum menyepakati keputusan. Proses ini mencerminkan ...', ['Permusyawaratan yang mempertimbangkan pendapat peserta.', 'Keputusan sepihak oleh pembicara pertama.', 'Penghapusan semua perbedaan pendapat.', 'Hak mutlak kelompok yang paling keras.', 'Larangan bagi minoritas menyampaikan usul.'], 'Musyawarah menuntut pertimbangan pendapat dan alasan. Suara keras atau urutan berbicara tidak menentukan kebenaran usul.'],
  ['PILAR_NEGARA', 'Bantuan pendidikan dibagikan berdasarkan kebutuhan dan kriteria terbuka, bukan kedekatan dengan pengurus. Nilai yang paling langsung diwujudkan adalah ...', ['Keadilan sosial.', 'Ketaatan kepada tokoh tanpa pertimbangan.', 'Keistimewaan kelompok tertentu.', 'Penyeragaman semua kemampuan.', 'Persaingan tanpa aturan.'], 'Kriteria kebutuhan yang terbuka mendukung pembagian kesempatan secara adil. Adil tidak selalu berarti pembagian sama tanpa mempertimbangkan kebutuhan.'],
  ['PILAR_NEGARA', 'Dalam negara yang menjunjung hukum, sengketa antarwarga sebaiknya diselesaikan dengan ...', ['Prosedur yang sah dan kesempatan yang adil bagi pihak terkait.', 'Ancaman dari pihak yang lebih kuat.', 'Penetapan kesalahan berdasarkan rumor.', 'Penghukuman oleh massa tanpa pemeriksaan.', 'Keputusan berdasarkan kekayaan pihak bersengketa.'], 'Penyelesaian yang sah melindungi para pihak dari kesewenang-wenangan. Rumor, ancaman, dan kekayaan bukan pengganti pemeriksaan yang adil.'],
  ['PILAR_NEGARA', 'Makna persatuan dalam masyarakat yang beragam paling tepat dijelaskan sebagai ...', ['Bekerja untuk tujuan bersama sambil menghormati perbedaan yang ada.', 'Menghapus semua budaya daerah.', 'Mengutamakan kepentingan satu suku.', 'Mewajibkan semua warga memiliki kebiasaan yang sama.', 'Mencegah warga berbeda kelompok bekerja sama.'], 'Persatuan memungkinkan kerja bersama dalam keberagaman. Persatuan tidak mensyaratkan penghapusan identitas atau kebiasaan daerah.'],
  ['BAHASA_NEGARA', 'Pilih kalimat efektif untuk pengumuman kehadiran.', ['Peserta diminta hadir pukul 08.00.', 'Para peserta-peserta diminta hadir pukul 08.00.', 'Peserta diminta agar supaya hadir pukul 08.00.', 'Bagi peserta diminta hadir pukul 08.00.', 'Peserta diminta hadir pada pukul jam 08.00.'], 'Kalimat yang dipilih memiliki subjek jelas dan tidak mengulang penanda jamak, tujuan, atau waktu secara berlebihan.'],
  ['BAHASA_NEGARA', 'Penulisan kata depan dan imbuhan yang tepat terdapat pada kalimat ...', ['Berkas disimpan di dalam lemari.', 'Berkas di simpan di dalam lemari.', 'Berkas disimpan didalam lemari.', 'Berkas di simpan didalam lemari.', 'Berkas di-simpan di dalam lemari.'], 'Imbuhan di- pada disimpan ditulis serangkai; kata depan di yang menunjukkan tempat ditulis terpisah dalam di dalam lemari.'],
  ['BAHASA_NEGARA', 'Bacalah: “Perpustakaan memperpanjang jam buka. Pengunjung kini dapat belajar hingga malam. Perubahan ini membantu warga yang bekerja pada siang hari.” Gagasan utama paragraf adalah ...', ['Perpanjangan jam buka perpustakaan membantu akses belajar warga.', 'Semua warga bekerja pada malam hari.', 'Perpustakaan menghapus layanan siang hari.', 'Pengunjung dilarang belajar di luar perpustakaan.', 'Jam kerja warga ditentukan perpustakaan.'], 'Kalimat-kalimat menjelaskan perubahan jam layanan dan manfaatnya. Tidak ada informasi tentang penghapusan layanan siang atau aturan jam kerja warga.'],
  ['BAHASA_NEGARA', 'Kata penghubung yang tepat: “Jalan utama tergenang, ... petugas mengalihkan kendaraan ke jalur alternatif.”', ['sehingga', 'meskipun', 'sedangkan', 'sebelum', 'andaikan'], 'Pengalihan kendaraan merupakan akibat jalan tergenang. Sehingga menghubungkan sebab dengan akibat pada kalimat ini.'],
  ['BAHASA_NEGARA', 'Kalimat “Warga wajib menyerahkan formulir paling lambat Jumat” berarti ...', ['Formulir boleh diserahkan sebelum atau pada Jumat.', 'Formulir hanya boleh diserahkan setelah Jumat.', 'Formulir tidak boleh diserahkan sebelum Jumat.', 'Penyerahan formulir bersifat sukarela.', 'Tidak ada batas waktu penyerahan formulir.'], 'Paling lambat menyatakan batas akhir. Kalimat tersebut tetap memperbolehkan penyerahan lebih awal.'],
  ['BAHASA_NEGARA', 'Pilih kalimat yang paling jelas menunjukkan bahwa hanya petugas beridentitas resmi boleh memasuki ruang arsip.', ['Hanya petugas yang memiliki identitas resmi boleh memasuki ruang arsip.', 'Petugas hanya memiliki identitas resmi boleh memasuki ruang arsip.', 'Petugas memiliki hanya identitas resmi memasuki ruang arsip.', 'Ruang arsip boleh memasuki petugas beridentitas resmi.', 'Identitas resmi memasuki ruang arsip hanya petugas.'], 'Penempatan hanya di awal membatasi kelompok yang diizinkan, sedangkan anak kalimat yang memiliki identitas resmi menjelaskan syarat petugas.']
];

export const tiu: Single[] = [
  ['NUMERIK_PERSENTASE', 'Harga tas Rp240.000 didiskon 15%. Berapa harga yang dibayar?', ['Rp204.000', 'Rp196.000', 'Rp216.000', 'Rp225.000', 'Rp276.000'], 'Diskon = 15/100 × 240.000 = 36.000. Harga akhir = 240.000 − 36.000 = Rp204.000.'],
  ['NUMERIK_PERBANDINGAN', 'Enam pekerja menyelesaikan pekerjaan dalam 12 hari. Dengan produktivitas sama dan pekerjaan dapat dibagi merata, delapan pekerja memerlukan ...', ['9 hari', '6 hari', '8 hari', '12 hari', '16 hari'], 'Beban pekerjaan = 6 × 12 = 72 hari-orang. Waktu untuk 8 pekerja = 72/8 = 9 hari.'],
  ['NUMERIK_RASIO', 'Perbandingan buku fiksi dan nonfiksi adalah 3 : 5. Jika totalnya 64 buku, jumlah buku nonfiksi adalah ...', ['40', '24', '32', '48', '56'], 'Ada 8 bagian. Tiap bagian 64/8 = 8 buku; nonfiksi 5 × 8 = 40 buku.'],
  ['NUMERIK_RATA_RATA', 'Nilai empat tes adalah 70, 80, 75, dan 85. Berapa nilai tes kelima agar rata-rata lima tes 80?', ['90', '80', '85', '95', '100'], 'Jumlah lima nilai harus 5 × 80 = 400. Jumlah empat nilai = 310, sehingga nilai kelima = 90.'],
  ['NUMERIK_KECEPATAN', 'Kendaraan menempuh 150 km dengan kecepatan tetap 60 km/jam, tanpa berhenti. Lama perjalanan adalah ...', ['2 jam 30 menit', '2 jam', '2 jam 15 menit', '3 jam', '3 jam 30 menit'], 'Waktu = jarak/kecepatan = 150/60 = 2,5 jam, yaitu 2 jam 30 menit.'],
  ['NUMERIK_PERSAMAAN', 'Jika 3x + 7 = 34, nilai x adalah ...', ['9', '7', '8', '11', '13'], 'Kurangi kedua ruas dengan 7: 3x = 27. Bagi dengan 3 sehingga x = 9.'],
  ['NUMERIK_PECAHAN', 'Nilai 3/4 + 2/3 adalah ...', ['17/12', '5/7', '5/12', '13/12', '7/12'], 'Samakan penyebut menjadi 12: 9/12 + 8/12 = 17/12.'],
  ['NUMERIK_DERET', 'Tentukan bilangan berikutnya: 3, 7, 15, 31, ...', ['63', '47', '60', '62', '64'], 'Setiap suku dikali 2 lalu ditambah 1. Setelah 31 diperoleh 31 × 2 + 1 = 63.'],
  ['NUMERIK_DERET', 'Tentukan bilangan berikutnya: 2, 6, 12, 20, 30, ...', ['42', '36', '40', '44', '48'], 'Selisih berturut-turut 4, 6, 8, 10. Selisih berikutnya 12, sehingga suku berikutnya 42.'],
  ['NUMERIK_PELUANG', 'Kantong berisi 4 bola merah dan 6 bola biru. Satu bola diambil secara acak, tiap bola berpeluang sama. Peluang mendapat bola merah adalah ...', ['2/5', '1/5', '3/5', '2/3', '4/6'], 'Ada 4 bola merah dari total 10. Peluang = 4/10 = 2/5.'],
  ['NUMERIK_GEOMETRI', 'Persegi panjang memiliki panjang 12 cm dan lebar 7 cm. Kelilingnya adalah ...', ['38 cm', '19 cm', '24 cm', '42 cm', '84 cm'], 'Keliling persegi panjang = 2 × (panjang + lebar) = 2 × 19 = 38 cm.'],
  ['NUMERIK_PERSENTASE', 'Jumlah pengunjung naik dari 80 menjadi 100 orang. Persentase kenaikannya adalah ...', ['25%', '20%', '40%', '80%', '125%'], 'Kenaikan 20 orang dibandingkan nilai awal 80. Persentase = 20/80 × 100% = 25%.'],
  ['NUMERIK_KERJA', 'Mesin A menyelesaikan satu pesanan dalam 6 jam dan mesin B dalam 3 jam. Jika bekerja bersama dengan laju tetap yang dapat dijumlahkan, pesanan selesai dalam ...', ['2 jam', '1 jam', '3 jam', '4,5 jam', '9 jam'], 'Laju gabungan = 1/6 + 1/3 = 1/2 pesanan per jam. Waktu satu pesanan = 2 jam.'],
  ['NUMERIK_SKALA', 'Pada peta berskala 1 : 200.000, jarak dua kota 4 cm. Jarak sebenarnya adalah ...', ['8 km', '0,8 km', '4 km', '20 km', '80 km'], 'Jarak sebenarnya = 4 × 200.000 = 800.000 cm. Karena 100.000 cm = 1 km, hasilnya 8 km.'],
  ['NUMERIK_PERBANDINGAN', 'Dua bilangan memiliki jumlah 48 dan selisih 12. Bilangan yang lebih besar adalah ...', ['30', '18', '24', '36', '42'], 'Jika a + b = 48 dan a − b = 12, maka 2a = 60 dan a = 30.'],
  ['VERBAL_ANALOGI', 'Hubungan “termometer : suhu” sepadan dengan ...', ['barometer : tekanan udara', 'jam : panjang', 'timbangan : warna', 'penggaris : massa', 'kompas : kelembapan'], 'Termometer mengukur suhu dan barometer mengukur tekanan udara. Pilihan lain memasangkan alat dengan besaran yang tidak diukurnya.'],
  ['VERBAL_ANALOGI', 'Hubungan “dokter : pasien” sepadan dengan ...', ['guru : murid', 'buku : pembaca', 'obat : apotek', 'papan : kapur', 'kelas : gedung'], 'Hubungannya adalah profesi dengan orang yang dilayani atau dibimbing. Guru membimbing murid sebagaimana dokter merawat pasien.'],
  ['VERBAL_ANALOGI', 'Hubungan “benih : tanaman” sepadan dengan ...', ['telur : ayam', 'daun : akar', 'susu : gelas', 'batu : pasir pantai', 'buku : rak'], 'Hubungan yang dimaksud adalah tahap awal yang berkembang menjadi organisme. Telur dapat berkembang menjadi ayam.'],
  ['VERBAL_SILOGISME', 'Semua arsip digital dicadangkan. Sebagian dokumen kantor merupakan arsip digital. Kesimpulan yang pasti benar adalah ...', ['Sebagian dokumen kantor dicadangkan.', 'Semua dokumen kantor dicadangkan.', 'Tidak ada dokumen kantor dicadangkan.', 'Semua cadangan merupakan dokumen kantor.', 'Dokumen kantor tidak dapat menjadi arsip digital.'], 'Sebagian dokumen termasuk kelompok arsip digital, dan seluruh kelompok tersebut dicadangkan. Premis tidak mencakup semua dokumen kantor.'],
  ['VERBAL_SILOGISME', 'Tidak ada kendaraan listrik di garasi A. Semua mobil dinas berada di garasi A. Kesimpulan yang pasti benar adalah ...', ['Tidak ada mobil dinas yang merupakan kendaraan listrik.', 'Semua kendaraan listrik merupakan mobil dinas.', 'Sebagian mobil dinas merupakan kendaraan listrik.', 'Semua kendaraan di garasi A merupakan mobil dinas.', 'Tidak ada kendaraan di garasi A.'], 'Mobil dinas berada di kelompok garasi A yang tidak beranggotakan kendaraan listrik. Tidak dapat disimpulkan bahwa semua isi garasi adalah mobil dinas.'],
  ['VERBAL_LOGIKA', 'Jika hujan, latihan dipindahkan ke aula. Latihan hari ini tidak dipindahkan ke aula. Berdasarkan kedua pernyataan tersebut, kesimpulannya ...', ['Hari ini tidak hujan.', 'Hari ini hujan.', 'Aula pasti rusak.', 'Latihan pasti dibatalkan.', 'Latihan selalu berada di aula.'], 'Ini bentuk modus tollens: jika P maka Q; bukan Q berarti bukan P. Kesimpulannya tidak hujan, tanpa menyimpulkan kondisi aula.'],
  ['VERBAL_LOGIKA', 'Jika berkas lengkap, permohonan diproses. Permohonan Rina diproses. Pernyataan yang tepat berdasarkan informasi itu adalah ...', ['Kelengkapan berkas Rina belum dapat dipastikan.', 'Berkas Rina pasti lengkap.', 'Berkas Rina pasti tidak lengkap.', 'Semua permohonan tidak lengkap diproses.', 'Tidak ada permohonan lengkap diproses.'], 'P → Q tidak berarti Q → P. Premis tidak menyatakan bahwa kelengkapan merupakan satu-satunya kondisi pemrosesan.'],
  ['VERBAL_ANALITIS', 'Dalam antrean, Ari berada sebelum Bima, dan Bima sebelum Citra. Pernyataan yang pasti benar adalah ...', ['Ari berada sebelum Citra.', 'Citra berada sebelum Ari.', 'Bima berada sebelum Ari.', 'Ari tepat di depan Citra.', 'Tidak ada orang lain di antrean.'], 'Urutan sebelum bersifat transitif. Informasi tidak menjamin kedekatan posisi atau jumlah seluruh orang dalam antrean.'],
  ['VERBAL_ANALITIS', 'Empat rapat berlangsung Senin sampai Kamis, satu per hari. A hari Senin, B tepat sehari setelah C, dan D hari Kamis. Hari rapat B adalah ...', ['Rabu', 'Senin', 'Selasa', 'Kamis', 'Jumat'], 'Hari tersisa Selasa dan Rabu untuk C dan B. Karena B tepat setelah C, C Selasa dan B Rabu.'],
  ['VERBAL_ANALITIS', 'Lima buku P, Q, R, S, T disusun berurutan. P pertama, T terakhir, Q tepat setelah P, dan S tepat sebelum T. Buku di tengah adalah ...', ['R', 'P', 'Q', 'S', 'T'], 'P di posisi 1, Q di 2, S di 4, dan T di 5. Posisi 3 tersisa untuk R.'],
  ['FIGURAL_ROTASI', 'Panah berputar 90° searah jarum jam tiap langkah: ↑, →, ↓, ... . Panah berikutnya adalah ...', ['←', '↑', '→', '↓', '↗'], 'Setelah panah bawah diputar 90° searah jarum jam, arahnya menjadi kiri.'],
  ['FIGURAL_POLA', 'Urutan bentuk mengulang tiga unsur: ○, △, □, ○, △, ... . Bentuk berikutnya adalah ...', ['□', '○', '△', '◇', '☆'], 'Satu siklus terdiri dari lingkaran, segitiga, persegi. Setelah unsur kedua pada siklus berikutnya muncul persegi.'],
  ['FIGURAL_ANALOGI', 'Pada pasangan bentuk, ○ berubah menjadi ● tanpa mengubah bentuk luar. Dengan aturan yang sama, □ berubah menjadi ...', ['■', '△', '◇', '○', '☆'], 'Perubahannya mengisi bagian dalam bentuk. Persegi kosong menjadi persegi terisi.'],
  ['FIGURAL_ANALOGI', 'Pasangan “△□ menjadi □△” menunjukkan pertukaran posisi. Dengan aturan yang sama, “○◇” menjadi ...', ['◇○', '○◇', '○○', '◇◇', '△○'], 'Dua unsur bertukar posisi tanpa berganti bentuk, sehingga belah ketupat mendahului lingkaran.'],
  ['FIGURAL_ROTASI', 'Tanda berbentuk └ diputar 90° searah jarum jam. Bentuk hasilnya adalah ...', ['┌', '└', '┐', '┘', '┼'], 'Dua lengan semula mengarah ke atas dan kanan. Setelah rotasi searah jarum jam, lengan mengarah ke kanan dan bawah: ┌.'],
  ['FIGURAL_CERMIN', 'Panah ↗ dicerminkan terhadap garis vertikal. Hasil pencerminannya adalah ...', ['↖', '↗', '↘', '↙', '↓'], 'Cermin vertikal menukar kiri dan kanan sementara arah atas tetap, sehingga kanan-atas menjadi kiri-atas.'],
  ['FIGURAL_CERMIN', 'Panah ↘ dicerminkan terhadap garis horizontal. Hasil pencerminannya adalah ...', ['↗', '↘', '↙', '↖', '←'], 'Cermin horizontal menukar atas dan bawah tanpa menukar kanan-kiri. Kanan-bawah menjadi kanan-atas.'],
  ['FIGURAL_ANALOGI', 'Pada pola “○△□ menjadi △□○”, unsur pertama dipindah ke akhir. Dengan aturan sama, “◇☆●” menjadi ...', ['☆●◇', '●◇☆', '◇●☆', '☆◇●', '◇☆●'], 'Memindahkan ◇ dari depan ke belakang mempertahankan urutan ☆ dan ●, menghasilkan ☆●◇.'],
  ['FIGURAL_POLA', 'Tiap langkah menambah satu lingkaran: ● ; ●● ; ●●● ; ... . Kelompok berikutnya adalah ...', ['●●●●', '●●', '●', '●●●●●', '●●●●●●'], 'Jumlah lingkaran bertambah dari 1 ke 2 ke 3, sehingga langkah berikutnya memiliki 4 lingkaran.'],
  ['FIGURAL_KLASIFIKASI', 'Bentuk mana yang berbeda dari empat lainnya karena memiliki garis lengkung?', ['○', '△', '□', '◇', '▱'], 'Lingkaran memiliki garis lengkung. Segitiga, persegi, belah ketupat, dan jajargenjang tersusun dari ruas garis lurus.']
];

export function makeSingle(sub: 'TWK' | 'TIU', tuple: Single, position: number): QuestionInput {
  const [topic, prompt, choices, explanation] = tuple;
  const shift = position % 5;
  const options = choices.map((_, i) => ({ code: 'ABCDE'[i] as 'A', text_md: choices[(i + shift) % 5] }));
  return {
    external_key: `CPNS-SKD-TRIAL-${String(position + 1).padStart(3, '0')}`,
    exam_type: 'CPNS', subtest_code: sub, formation_code: null, topic_code: topic,
    difficulty: 'medium', prompt_md: prompt, scoring_mode: 'single_correct', options,
    correct_option_code: options.find(o => o.text_md === choices[0])!.code,
    score_correct: 5, score_wrong: 0, score_blank: 0, explanation_md: explanation,
    shuffle_options: true, assets: [], source_note: 'Latihan orisinal Ruang Tryout; cakupan subtes mengacu KepmenPANRB 321/2024 (BKN). Bukan soal resmi atau kisi-kisi resmi 2027. Materi disusun untuk uji lokal; tinjauan editor manusia belum dilakukan.',
    rights_basis: 'Disusun khusus untuk proyek ini; tidak menyalin bank soal pihak ketiga.'
  };
}
